"""Add conversation memory system

Revision ID: 029d392fd948
Revises: aa9a47b3b4e2
Create Date: 2025-09-24 00:32:21.131485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029d392fd948'
down_revision = 'aa9a47b3b4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('conversation_session', schema=None) as batch_op:
        batch_op.create_index('idx_user_active_session', ['user_id', 'is_active'], unique=False)

    op.create_table('conversation_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=True),
    sa.Column('optimization_level', sa.String(length=20), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_session.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_message', schema=None) as batch_op:
        batch_op.create_index('idx_session_created', ['session_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_message', schema=None) as batch_op:
        batch_op.drop_index('idx_session_created')

    op.drop_table('conversation_message')
    with op.batch_alter_table('conversation_session', schema=None) as batch_op:
        batch_op.drop_index('idx_user_active_session')

    op.drop_table('conversation_session')
    # ### end Alembic commands ###
