"""update transaction and PDFExtractable relationship

Revision ID: 83d5b620c9c1
Revises: ea5d361a01b2
Create Date: 2025-06-01 01:54:55.733264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d5b620c9c1'
down_revision = 'ea5d361a01b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('transaction_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pdf_extractable', ['pdf_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('pdf_id')

    # ### end Alembic commands ###
