"""add pdf_content_oid column

Revision ID: a1e39405b773
Revises: 76493ff201cf
Create Date: 2025-10-18 19:55:44.857935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1e39405b773'
down_revision = '76493ff201cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_extractable', schema=None) as batch_op:
        batch_op.alter_column('pdf_content_oid',
               existing_type=postgresql.OID(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='OID reference to PDF',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_extractable', schema=None) as batch_op:
        batch_op.alter_column('pdf_content_oid',
               existing_type=sa.Integer(),
               type_=postgresql.OID(),
               comment='OID reference to PDF',
               existing_nullable=True)

    # ### end Alembic commands ###
