"""Add enhanced fields to transaction table

Revision ID: aa9a47b3b4e2
Revises: 83d5b620c9c1
Create Date: 2025-09-23 14:50:01.866601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9a47b3b4e2'
down_revision = '83d5b620c9c1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_original',
                            sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(
            sa.Column('merchant', sa.String(length=200), nullable=True))
        # Add boolean column as nullable first
        batch_op.add_column(
            sa.Column('is_installment', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('installment_info',
                            sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(
        ), server_default=sa.text('now()'), nullable=True))

    # Update all existing records to have is_installment = False
    op.execute(
        "UPDATE transaction SET is_installment = FALSE WHERE is_installment IS NULL")

    # Now make the column NOT NULL
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('is_installment', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('installment_info')
        batch_op.drop_column('is_installment')
        batch_op.drop_column('merchant')
        batch_op.drop_column('category')
        batch_op.drop_column('description_original')

    # ### end Alembic commands ###
