"""Add PDFExtractable and Card models

Revision ID: ea5d361a01b2
Revises: dd45935cf6de
Create Date: 2025-06-01 01:43:48.655695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea5d361a01b2'
down_revision = 'dd45935cf6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('expiration_date', sa.String(length=10), nullable=False),
    sa.Column('card_type', sa.String(length=16), nullable=False),
    sa.Column('available_limit', sa.Float(), nullable=True),
    sa.Column('used_limit', sa.Float(), nullable=True),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdf_extractable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('statement_date', sa.String(length=20), nullable=True),
    sa.Column('statement_period_start', sa.String(length=20), nullable=True),
    sa.Column('statement_period_end', sa.String(length=20), nullable=True),
    sa.Column('previous_invoice', sa.Float(), nullable=True),
    sa.Column('payment_received', sa.Float(), nullable=True),
    sa.Column('total_purchases', sa.Float(), nullable=True),
    sa.Column('other_charges', sa.Float(), nullable=True),
    sa.Column('total_to_pay', sa.Float(), nullable=True),
    sa.Column('next_closing_date', sa.String(length=20), nullable=True),
    sa.Column('next_invoice_balance', sa.Float(), nullable=True),
    sa.Column('total_open_balance', sa.Float(), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_extractable')
    op.drop_table('card')
    # ### end Alembic commands ###
