"""add file_hash to pdf_extractable for duplicate detection

Revision ID: f1a2b3c4d5e6
Revises: 83d5b620c9c1
Create Date: 2025-01-14 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = '83d5b620c9c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_extractable', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('file_hash', sa.String(length=32), nullable=True))
        batch_op.create_index('ix_pdf_extractable_file_hash', [
                              'file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_extractable', schema=None) as batch_op:
        batch_op.drop_index('ix_pdf_extractable_file_hash')
        batch_op.drop_column('file_hash')

    # ### end Alembic commands ###
